'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''lblBubbleGumCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBubbleGumCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDoubleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDoubleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTripleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTripleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLemonDropCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLemonDropCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOatmealChocolateChunkCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOatmealChocolateChunkCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOatmealCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOatmealCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPeanutButterChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeanutButterChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPeanutButterMapleCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeanutButterMapleCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVanillaBeanSugarCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVanillaBeanSugarCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWhiteChocolateMacadamiaCranberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWhiteChocolateMacadamiaCranberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWhiteChocolateRaspberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWhiteChocolateRaspberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTexasSheetCake As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblChocolateFudgeBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChocolateFudgeBrownies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMillionDollarFudge As Global.System.Web.UI.WebControls.Label
End Class
