'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Order
    
    '''<summary>
    '''UpdatePanel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel18 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblBubbleGumAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBubbleGumAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbBubbleGumAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBubbleGumAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel31 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountBubbleGum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountBubbleGum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderBubbleGum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderBubbleGum As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedIntoOrderBubbleGumCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedIntoOrderBubbleGumCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel19 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblChocolateChipAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChocolateChipAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbChocolateChipAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChocolateChipAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel32 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountChocolateChip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountChocolateChip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderChocolateChip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderChocolateChip As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel20 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblDoubleChocolateAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDoubleChocolateAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDoubleChocolateAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDoubleChocolateAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel33 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountDoubleChocolate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountDoubleChocolate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderDoubleChocolate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderDoubleChocolate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderDoubleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderDoubleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel21 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblTripleChocolateAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTripleChocolateAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbTripleChocolateAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTripleChocolateAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel34 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountTripleChocolate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountTripleChocolate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderTripleChocolate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderTripleChocolate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderTripleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderTripleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel22 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblLemonDropAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLemonDropAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbLemonDropAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLemonDropAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel35 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountLemonDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountLemonDrop As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderLemonDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderLemonDrop As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderLemonDropCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderLemonDropCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel23 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblOatmealChocolateChunkAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOatmealChocolateChunkAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbOatmealChocolateChunkAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOatmealChocolateChunkAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel36 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountOatmealChocolateChunk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountOatmealChocolateChunk As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderOatmealChocolateChunk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderOatmealChocolateChunk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderOatmealChocolateChunkCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderOatmealChocolateChunkCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel24 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblOatmealAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOatmealAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbOatmealAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOatmealAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel37 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountOatmeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountOatmeal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel8 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderOatmeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderOatmeal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderOatmealCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderOatmealCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel25 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblPeanutButterChocolateChipAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeanutButterChocolateChipAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbPeanutButterChocolateChipAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPeanutButterChocolateChipAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel38 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountPeanutButterChocolateChip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountPeanutButterChocolateChip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel9 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderPeanutButterChocolateChip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderPeanutButterChocolateChip As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderPeanutButterChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderPeanutButterChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel26 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblPeanutButterMapleAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeanutButterMapleAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbPeanutButterMapleAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPeanutButterMapleAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel39 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountPeanutButterMaple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountPeanutButterMaple As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel10 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderPeanutButterMaple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderPeanutButterMaple As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderPeanutButterMapleCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderPeanutButterMapleCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel27 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblVanillaBeanSugarAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVanillaBeanSugarAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbVanillaBeanSugarAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVanillaBeanSugarAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel40 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountVanillaBeanSugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountVanillaBeanSugar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel11 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderVanillaBeanSugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderVanillaBeanSugar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderVanillaBeanSugarCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderVanillaBeanSugarCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel28 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblWhiteChocolateMacadamiaCranberryAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWhiteChocolateMacadamiaCranberryAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbWhiteChocolateMacadamiaCranberryAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWhiteChocolateMacadamiaCranberryAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel41 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountWhiteChocolateMacadamiaCranberry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountWhiteChocolateMacadamiaCranberry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel12 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderWhiteChocolateMacadamiaCranberry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderWhiteChocolateMacadamiaCranberry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderWhiteChocolateMacadamiaCranberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderWhiteChocolateMacadamiaCranberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel29 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblWhiteChocolateRaspberryAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWhiteChocolateRaspberryAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbWhiteChocolateRaspberryAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWhiteChocolateRaspberryAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel42 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountWhiteChocolateRaspberry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountWhiteChocolateRaspberry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel13 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderWhiteChocolateRaspberry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderWhiteChocolateRaspberry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderWhiteChocolateRaspberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderWhiteChocolateRaspberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel43 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountTexasSheetCake As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel14 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderTexasSheetCake As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderTexasSheetCake As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel30 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblChocolateFudgeBrownieAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChocolateFudgeBrownieAddPecans As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbChocolateFudgeBrownieAddPecans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChocolateFudgeBrownieAddPecans As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdatePanel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel44 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountChocolateFudgeBrownie As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel15 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderChocolateFudgeBrownie As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderChocolateFudgeBrownie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel45 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel16 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel46 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tbCountMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountMillionDollarFudge As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UpdatePanel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel17 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnOrderMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrderMillionDollarFudge As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAddedToOrderMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddedToOrderMillionDollarFudge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phNothingOrdered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phNothingOrdered As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''phBubbleGumCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phBubbleGumCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalBubbleGumCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalBubbleGumCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalBubbleGumCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalBubbleGumCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForBubbleGumCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForBubbleGumCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteBubbleGumCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteBubbleGumCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phChocolateChipCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalChocolateChipCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteChocolateChipCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteChocolateChipCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phDoubleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phDoubleChocolateCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalDoubleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalDoubleChocolateCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalDoubleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalDoubleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForDoubleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForDoubleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteDoubleChocolateCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteDoubleChocolateCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phTripleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTripleChocolateCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalTripleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalTripleChocolateCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalTripleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalTripleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForTripleChocolateCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForTripleChocolateCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteTripleChocolateCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteTripleChocolateCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phLemonDropCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phLemonDropCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalLemonDropCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalLemonDropCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalLemonDropCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalLemonDropCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForLemonDropCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForLemonDropCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteLemonDropCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteLemonDropCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phOatmealChocolateChunkCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phOatmealChocolateChunkCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalOatmealChocloateChunkCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalOatmealChocloateChunkCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalOatmealChocolateChunkCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalOatmealChocolateChunkCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForOatmealChocolateChunkCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForOatmealChocolateChunkCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteOatmealChocolateChunkCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOatmealChocolateChunkCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phOatmealCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phOatmealCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalOatmealCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalOatmealCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalOatmealCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalOatmealCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForOatmealCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForOatmealCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteOatmealCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOatmealCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phPeanutButterChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPeanutButterChocolateChipCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalPeanutButterChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalPeanutButterChocolateChipCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalPeanutButterChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalPeanutButterChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForPeanutButterChocolateChipCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForPeanutButterChocolateChipCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeletePeanutButterChocolateChipCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePeanutButterChocolateChipCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phPeanutButterMapleCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPeanutButterMapleCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalPeanutButterMapleCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalPeanutButterMapleCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalPeanutButterMapleCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalPeanutButterMapleCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForPeanutButterMapleCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForPeanutButterMapleCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeletePeanutButterMapleCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePeanutButterMapleCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phVanillaBeanSugarCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phVanillaBeanSugarCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalVanillaBeanSugarCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalVanillaBeanSugarCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalVanillaBeanSugarCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalVanillaBeanSugarCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForVanillaBeanSugarCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForVanillaBeanSugarCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteVanillaBeanSugarCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteVanillaBeanSugarCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phWhiteChocolateMacadamiaCranberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phWhiteChocolateMacadamiaCranberryCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalWhiteChocolateMacadamiaCranberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalWhiteChocolateMacadamiaCranberryCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalWhiteChocolateMacadamiaCranberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalWhiteChocolateMacadamiaCranberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForWhiteChocolateMacadamiaCranberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForWhiteChocolateMacadamiaCranberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteWhiteChocolateMacadamiaCranberryCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteWhiteChocolateMacadamiaCranberryCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phWhiteChocolateRaspberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phWhiteChocolateRaspberryCookies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalWhiteChocolateRaspberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalWhiteChocolateRaspberryCookies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalWhiteChocolateRaspberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalWhiteChocolateRaspberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForWhiteChocolateRaspberryCookies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForWhiteChocolateRaspberryCookies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteWhiteChocolateRaspberryCookiesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteWhiteChocolateRaspberryCookiesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTexasSheetCake As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalTexasSheetCake As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalTexasSheetCake As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForTexasSheetCake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForTexasSheetCake As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteTexasSheetCakeFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteTexasSheetCakeFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phChocolateFudgeBrownie As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalChocolateFudgeBrownie As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalChocolateFudgeBrownie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForChocolateFudgeBrownie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForChocolateFudgeBrownie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteChocolateFudgeBrownieFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteChocolateFudgeBrownieFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForChocolateCaramelPecanBrownies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForChocolateCaramelPecanBrownies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteChocolateCaramelPecanBrowniesFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteChocolateCaramelPecanBrowniesFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phMillionDollarFudge As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lForOrderTotalMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lForOrderTotalMillionDollarFudge As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderTotalMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderTotalMillionDollarFudge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriceForMillionDollarFudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceForMillionDollarFudge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteMillionDollarFudgeFromOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteMillionDollarFudgeFromOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phTotalPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTotalPrice As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblTotalPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnPlaceOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPlaceOrder As Global.System.Web.UI.WebControls.Button
End Class
